import {
  CalendarCheck,
  CalendarClock,
  ChartColumn,
  Check,
  Clock,
  CreditCard,
  Crown,
  Gem,
  Gift,
  Globe,
  Headset,
  Layers,
  LayoutTemplate,
  MessagesSquare,
  PiggyBank,
  Rocket,
  ShieldCheck,
  Sparkles,
  Star,
  TrendingUp,
  Users,
  Wallet,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { IconKey } from '@/payload/fields/icon'

// Options (with admin labels) are in src/payload/fields/icon.ts.
export const icons: Record<IconKey, LucideIcon> = {
  crm: Users,
  website: LayoutTemplate,
  automation: Workflow,
  messages: MessagesSquare,
  social: CalendarClock,
  payments: CreditCard,
  ai: Sparkles,
  reports: ChartColumn,
  check: Check,
  gift: Gift,
  zap: Zap,
  layers: Layers,
  rocket: Rocket,
  star: Star,
  crown: Crown,
  gem: Gem,
  shield: ShieldCheck,
  clock: Clock,
  wallet: Wallet,
  piggy: PiggyBank,
  trending: TrendingUp,
  calendar: CalendarCheck,
  headset: Headset,
  globe: Globe,
}
